// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ch6F61JsLkFLOkBpXEaA4tue_wTjagM',
    appId: '1:174596389364:web:76c649d3a8c60737c961a1',
    messagingSenderId: '174596389364',
    projectId: 'webcomu',
    authDomain: 'webcomu.firebaseapp.com',
    storageBucket: 'webcomu.appspot.com',
    measurementId: 'G-XCQQWTWDTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUxcQ10fR9ieS_CCxHhomr_pDujXnodaw',
    appId: '1:174596389364:android:a3f0548a9e42286fc961a1',
    messagingSenderId: '174596389364',
    projectId: 'webcomu',
    storageBucket: 'webcomu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8LaxNMMmxujJihHuLA_wKLeWWkvXpuM',
    appId: '1:174596389364:ios:793e1cb387f4999ec961a1',
    messagingSenderId: '174596389364',
    projectId: 'webcomu',
    storageBucket: 'webcomu.appspot.com',
    iosBundleId: 'com.example.webcomu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo8LaxNMMmxujJihHuLA_wKLeWWkvXpuM',
    appId: '1:174596389364:ios:793e1cb387f4999ec961a1',
    messagingSenderId: '174596389364',
    projectId: 'webcomu',
    storageBucket: 'webcomu.appspot.com',
    iosBundleId: 'com.example.webcomu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Ch6F61JsLkFLOkBpXEaA4tue_wTjagM',
    appId: '1:174596389364:web:90d2a445def4828fc961a1',
    messagingSenderId: '174596389364',
    projectId: 'webcomu',
    authDomain: 'webcomu.firebaseapp.com',
    storageBucket: 'webcomu.appspot.com',
    measurementId: 'G-51E1XH48LV',
  );
}
